# PROJECT: Time Series Forcasting By using Recurrent Neural Network.

# Import  Important Libraries

In [1]:
import pandas as pd
import numpy as np

# Read Google Stock Price Dataset

In [2]:
A = pd.read_csv("C:/Users/JOHN/Downloads/Google_Stock_Price_Train.csv")
A 
# This Format is called OHLC format 
# O --> Opening price of the stock
# H --> Highest price of the stock
# L --> low price of the Stock
# C --> Closing price of the stock

            Date    Open    High     Low   Close      Volume
0       1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1       1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2       1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3       1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4       1/9/2012  322.04  322.29  309.46  620.76  11,688,800
...          ...     ...     ...     ...     ...         ...
1253  12/23/2016  790.90  792.74  787.28  789.91     623,400
1254  12/27/2016  790.68  797.86  787.66  791.55     789,100
1255  12/28/2016  793.70  794.23  783.20  785.05   1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79     744,300
1257  12/30/2016  782.75  782.78  770.41  771.82   1,770,000

[1258 rows x 6 columns]

# Missing data Treatment

In [3]:
A.isna().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [4]:
# No missing values in a dataset

# Get Stock Opening Price

In [5]:
tr_data = A[["Open"]]

In [6]:
tr_data

        Open
0     325.25
1     331.27
2     329.83
3     328.34
4     322.04
...      ...
1253  790.90
1254  790.68
1255  793.70
1256  783.33
1257  782.75

[1258 rows x 1 columns]

# Scaling the data by MinMaxScaler

In [7]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
scaled_tr_data = mm.fit_transform(tr_data)
scaled_tr_data

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

# Create data for training  in such way that 50 rows as input and 51 row will be output

In [8]:
tr_data.head()

     Open
0  325.25
1  331.27
2  329.83
3  328.34
4  322.04

In [9]:
tr_data.shape

(1258, 1)

In [10]:
xtrain = []
ytrain = []
for i in range(50,1258,1):
    xtrain.append(tr_data[i-50:i]) # 50 rows as input
    ytrain.append(tr_data[i:i+1]) # 51 row will be output

In [11]:
print(xtrain[0],"\n") 
print(ytrain[0])

      Open
0   325.25
1   331.27
2   329.83
3   328.34
4   322.04
5   313.70
6   310.59
7   314.43
8   311.96
9   314.81
10  312.14
11  319.30
12  294.16
13  291.91
14  292.07
15  287.68
16  284.92
17  284.32
18  287.95
19  290.41
20  291.38
21  291.34
22  294.23
23  296.39
24  302.44
25  303.18
26  304.87
27  302.81
28  304.11
29  304.63
30  305.32
31  300.28
32  301.36
33  300.81
34  304.84
35  302.37
36  302.54
37  302.16
38  303.86
39  308.14
40  309.97
41  309.84
42  309.06
43  302.89
44  303.39
45  303.88
46  302.84
47  298.88
48  303.24
49  306.35

      Open
50  307.15

In [ ]:
# data prepared for trainning

In [12]:
type(xtrain)

list

In [13]:
xtr = np.array(xtrain)# Neural Network always treated data in the form of array
ytr = np.array(ytrain)

In [14]:
xtr

array([[[325.25],
        [331.27],
        [329.83],
        ...,
        [298.88],
        [303.24],
        [306.35]],

       [[331.27],
        [329.83],
        [328.34],
        ...,
        [303.24],
        [306.35],
        [307.15]],

       [[329.83],
        [328.34],
        [322.04],
        ...,
        [306.35],
        [307.15],
        [309.29]],

       ...,

       [[779.8 ],
        [787.85],
        [798.24],
        ...,
        [792.36],
        [790.9 ],
        [790.68]],

       [[787.85],
        [798.24],
        [803.3 ],
        ...,
        [790.9 ],
        [790.68],
        [793.7 ]],

       [[798.24],
        [803.3 ],
        [795.  ],
        ...,
        [790.68],
        [793.7 ],
        [783.33]]])

In [15]:
ytr

array([[[307.15]],

       [[309.29]],

       [[310.4 ]],

       ...,

       [[793.7 ]],

       [[783.33]],

       [[782.75]]])

In [16]:
xtr.shape

(1208, 50, 1)

In [17]:
ytr.shape

(1208, 1, 1)

# Create a Recurrent Neural Network Model

In [18]:
from keras.models import Sequential
from keras.layers import LSTM,Dense,Dropout
from keras.callbacks import EarlyStopping

In [19]:
es = EarlyStopping(patience=5,monitor = "loss")
nn = Sequential()
nn.add(LSTM(50,return_sequences = True,input_shape = (50,1)))
nn.add(Dense(100))
nn.add(Dense(1))
nn.compile(optimizer="adam",loss = "mean_squared_error")
nn.fit(xtr,ytr,epochs=10000,callbacks=es)

Epoch 1/10000
38/38 [==============================] - 4s 32ms/step - loss: 311000.6250
Epoch 2/10000
38/38 [==============================] - 1s 32ms/step - loss: 291215.4375
Epoch 3/10000
38/38 [==============================] - 1s 33ms/step - loss: 254540.3125
Epoch 4/10000
38/38 [==============================] - 1s 35ms/step - loss: 209550.1250
Epoch 5/10000
38/38 [==============================] - 1s 33ms/step - loss: 158937.1875
Epoch 6/10000
38/38 [==============================] - 1s 33ms/step - loss: 110510.0703
Epoch 7/10000
38/38 [==============================] - 1s 34ms/step - loss: 70418.9375
Epoch 8/10000
38/38 [==============================] - 1s 35ms/step - loss: 44531.7148
Epoch 9/10000
38/38 [==============================] - 1s 33ms/step - loss: 30815.0801
Epoch 10/10000
38/38 [==============================] - 1s 32ms/step - loss: 24408.3047
Epoch 11/10000
38/38 [==============================] - 1s 34ms/step - loss: 19835.8418
Epoch 12/10000
38/38 [==============================] - 1s 33ms/step - loss: 14916.7803
Epoch 13/10000
38/38 [==============================] - 1s 35ms/step - loss: 10646.7363
Epoch 14/10000
38/38 [==============================] - 1s 35ms/step - loss: 7589.8789
Epoch 15/10000
38/38 [==============================] - 1s 35ms/step - loss: 5614.0015
Epoch 16/10000
38/38 [==============================] - 1s 34ms/step - loss: 4431.4873
Epoch 17/10000
38/38 [==============================] - 1s 32ms/step - loss: 3855.6096
Epoch 18/10000
38/38 [==============================] - 1s 33ms/step - loss: 3277.5566
Epoch 19/10000
38/38 [==============================] - 1s 33ms/step - loss: 2836.7153
Epoch 20/10000
38/38 [==============================] - 1s 33ms/step - loss: 2639.4451
Epoch 21/10000
38/38 [==============================] - 1s 33ms/step - loss: 2514.5745
Epoch 22/10000
38/38 [==============================] - 1s 34ms/step - loss: 2397.2043
Epoch 23/10000
38/38 [==============================] - 1s 33ms/step - loss: 2227.0464
Epoch 24/10000
38/38 [==============================] - 1s 36ms/step - loss: 2133.0916
Epoch 25/10000
38/38 [==============================] - 1s 33ms/step - loss: 2120.5183
Epoch 26/10000
38/38 [==============================] - 1s 33ms/step - loss: 2011.5995
Epoch 27/10000
38/38 [==============================] - 1s 36ms/step - loss: 2012.4385
Epoch 28/10000
38/38 [==============================] - 1s 33ms/step - loss: 2013.7449
Epoch 29/10000
38/38 [==============================] - 1s 33ms/step - loss: 1958.5669
Epoch 30/10000
38/38 [==============================] - 1s 35ms/step - loss: 1885.4419
Epoch 31/10000
38/38 [==============================] - 1s 35ms/step - loss: 1976.0396
Epoch 32/10000
38/38 [==============================] - 1s 35ms/step - loss: 1934.5004
Epoch 33/10000
38/38 [==============================] - 1s 36ms/step - loss: 1920.6345
Epoch 34/10000
38/38 [==============================] - 1s 39ms/step - loss: 1833.2109
Epoch 35/10000
38/38 [==============================] - 1s 35ms/step - loss: 1826.1667
Epoch 36/10000
38/38 [==============================] - 1s 34ms/step - loss: 1902.2327
Epoch 37/10000
38/38 [==============================] - 1s 33ms/step - loss: 1820.2700
Epoch 38/10000
38/38 [==============================] - 1s 37ms/step - loss: 1865.2197
Epoch 39/10000
38/38 [==============================] - 1s 38ms/step - loss: 1824.5325
Epoch 40/10000
38/38 [==============================] - 1s 36ms/step - loss: 1877.0468
Epoch 41/10000
38/38 [==============================] - 1s 33ms/step - loss: 1917.7434
Epoch 42/10000
38/38 [==============================] - 1s 33ms/step - loss: 1874.2925

# Read Testing dataset

In [20]:
tsd = pd.read_csv("C:/Users/JOHN/Downloads/Google_Stock_Price_Test.csv")
tsd.head(7)

        Date    Open    High     Low   Close     Volume
0   1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1   1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2   1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3   1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4   1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5  1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6  1/11/2017  805.00  808.15  801.37  807.91  1,065,900

# Missing data treatment

In [21]:
tsd.isna().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [ ]:
# there is no missing data in testing set

In [67]:
tsd

         Date    Open    High     Low   Close     Volume
0    1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1    1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2    1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3    1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4    1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5   1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6   1/11/2017  805.00  808.15  801.37  807.91  1,065,900
7   1/12/2017  807.14  807.39  799.17  806.36  1,353,100
8   1/13/2017  807.48  811.22  806.69  807.88  1,099,200
9   1/17/2017  807.08  807.14  800.37  804.61  1,362,100
10  1/18/2017  805.81  806.21  800.99  806.07  1,294,400
11  1/19/2017  805.12  809.48  801.80  802.17    919,300
12  1/20/2017  806.91  806.91  801.69  805.02  1,670,000
13  1/23/2017  807.25  820.87  803.74  819.31  1,963,600
14  1/24/2017  822.30  825.90  817.82  823.87  1,474,000
15  1/25/2017  829.62  835.77  825.06  835.67  1,494,500
16  1/26/2017  837.81  838.00  827.01  832.15  2,973,900
17  1/27/2017  834.71  841.95  820.44  823.31  2,965,800
18  1/30/2017  814.66  815.84  799.80  802.32  3,246,600
19  1/31/2017  796.86  801.25  790.52  796.79  2,160,600

# Get Open Price for testing

In [22]:
tsd[["Open"]]

      Open
0   778.81
1   788.36
2   786.08
3   795.26
4   806.40
5   807.86
6   805.00
7   807.14
8   807.48
9   807.08
10  805.81
11  805.12
12  806.91
13  807.25
14  822.30
15  829.62
16  837.81
17  834.71
18  814.66
19  796.86

In [23]:
tsd.shape

(20, 6)

# concat two columns

In [24]:
Q = pd.concat([A,tsd])
Q.index = range(0,1278)

In [25]:
Q[["Open"]]

        Open
0     325.25
1     331.27
2     329.83
3     328.34
4     322.04
...      ...
1273  829.62
1274  837.81
1275  834.71
1276  814.66
1277  796.86

[1278 rows x 1 columns]

In [26]:
Q = Q[["Open"]].values # data in the form of an array

In [27]:
Q

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [834.71],
       [814.66],
       [796.86]])

In [28]:
xtest = []
for i in range(1258,1277,1):
    xtest.append(Q[i-50:i])

In [29]:
type(xtest)

list

In [30]:
type(xtr)

numpy.ndarray

In [31]:
# we will have to convert xtest into same type of xtr

In [32]:
xts = np.array(xtest)

In [33]:
xts

array([[[803.3 ],
        [795.  ],
        [804.9 ],
        [816.68],
        [806.34],
        [801.  ],
        [808.35],
        [795.47],
        [782.89],
        [778.2 ],
        [767.25],
        [750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75]],

       [[795.  ],
        [804.9 ],
        [816.68],
        [806.34],
        [801.  ],
        [808.35],
        [795.47],
        [782.89],
        [778.2 ],
        [767.25],
        [750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81]],

       [[804.9 ],
        [816.68],
        [806.34],
        [801.  ],
        [808.35],
        [795.47],
        [782.89],
        [778.2 ],
        [767.25],
        [750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36]],

       [[816.68],
        [806.34],
        [801.  ],
        [808.35],
        [795.47],
        [782.89],
        [778.2 ],
        [767.25],
        [750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08]],

       [[806.34],
        [801.  ],
        [808.35],
        [795.47],
        [782.89],
        [778.2 ],
        [767.25],
        [750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26]],

       [[801.  ],
        [808.35],
        [795.47],
        [782.89],
        [778.2 ],
        [767.25],
        [750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ]],

       [[808.35],
        [795.47],
        [782.89],
        [778.2 ],
        [767.25],
        [750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86]],

       [[795.47],
        [782.89],
        [778.2 ],
        [767.25],
        [750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ]],

       [[782.89],
        [778.2 ],
        [767.25],
        [750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ],
        [807.14]],

       [[778.2 ],
        [767.25],
        [750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ],
        [807.14],
        [807.48]],

       [[767.25],
        [750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ],
        [807.14],
        [807.48],
        [807.08]],

       [[750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ],
        [807.14],
        [807.48],
        [807.08],
        [805.81]],

       [[774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ],
        [807.14],
        [807.48],
        [807.08],
        [805.81],
        [805.12]],

       [[783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ],
        [807.14],
        [807.48],
        [807.08],
        [805.81],
        [805.12],
        [806.91]],

       [[779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ],
        [807.14],
        [807.48],
        [807.08],
        [805.81],
        [805.12],
        [806.91],
        [807.25]],

       [[791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ],
        [807.14],
        [807.48],
        [807.08],
        [805.81],
        [805.12],
        [806.91],
        [807.25],
        [822.3 ]],

       [[756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ],
        [807.14],
        [807.48],
        [807.08],
        [805.81],
        [805.12],
        [806.91],
        [807.25],
        [822.3 ],
        [829.62]],

       [[755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ],
        [807.14],
        [807.48],
        [807.08],
        [805.81],
        [805.12],
        [806.91],
        [807.25],
        [822.3 ],
        [829.62],
        [837.81]],

       [[746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75],
        [778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ],
        [807.14],
        [807.48],
        [807.08],
        [805.81],
        [805.12],
        [806.91],
        [807.25],
        [822.3 ],
        [829.62],
        [837.81],
        [834.71]]])

In [34]:
type(xts)

numpy.ndarray

In [35]:
xts.shape

(19, 50, 1)

In [36]:
tsd

         Date    Open    High     Low   Close     Volume
0    1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1    1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2    1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3    1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4    1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5   1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6   1/11/2017  805.00  808.15  801.37  807.91  1,065,900
7   1/12/2017  807.14  807.39  799.17  806.36  1,353,100
8   1/13/2017  807.48  811.22  806.69  807.88  1,099,200
9   1/17/2017  807.08  807.14  800.37  804.61  1,362,100
10  1/18/2017  805.81  806.21  800.99  806.07  1,294,400
11  1/19/2017  805.12  809.48  801.80  802.17    919,300
12  1/20/2017  806.91  806.91  801.69  805.02  1,670,000
13  1/23/2017  807.25  820.87  803.74  819.31  1,963,600
14  1/24/2017  822.30  825.90  817.82  823.87  1,474,000
15  1/25/2017  829.62  835.77  825.06  835.67  1,494,500
16  1/26/2017  837.81  838.00  827.01  832.15  2,973,900
17  1/27/2017  834.71  841.95  820.44  823.31  2,965,800
18  1/30/2017  814.66  815.84  799.80  802.32  3,246,600
19  1/31/2017  796.86  801.25  790.52  796.79  2,160,600

# Prediction

In [37]:
pred_data = nn.predict(xts)

In [38]:
pred_data

array([[[611.7007 ],
        [692.0161 ],
        [716.6562 ],
        [731.54895],
        [739.54346],
        [745.25397],
        [750.8436 ],
        [751.983  ],
        [751.8307 ],
        [752.2811 ],
        [750.8493 ],
        [747.3229 ],
        [753.11365],
        [755.146  ],
        [754.5792 ],
        [756.76276],
        [749.42896],
        [749.0326 ],
        [746.63904],
        [748.55383],
        [751.21155],
        [752.07465],
        [749.9401 ],
        [752.07324],
        [750.90344],
        [749.9458 ],
        [748.76996],
        [751.2976 ],
        [750.87836],
        [747.70404],
        [744.0111 ],
        [747.28235],
        [748.8539 ],
        [747.7661 ],
        [750.29236],
        [751.84406],
        [752.8093 ],
        [754.4632 ],
        [755.09436],
        [755.0825 ],
        [755.60315],
        [753.76764],
        [754.9058 ],
        [754.7188 ],
        [754.03436],
        [753.70337],
        [753.59753],
        [754.08655],
        [752.0292 ],
        [751.8084 ]],

       [[611.52625],
        [692.8374 ],
        [718.02454],
        [730.28296],
        [738.7793 ],
        [746.3091 ],
        [748.88257],
        [749.7301 ],
        [750.85565],
        [749.8917 ],
        [746.6839 ],
        [752.66943],
        [754.84875],
        [754.38794],
        [756.6428 ],
        [749.3632 ],
        [748.9972 ],
        [746.62476],
        [748.55304],
        [751.22205],
        [752.0959 ],
        [749.9706 ],
        [752.109  ],
        [750.94556],
        [749.99255],
        [748.8205 ],
        [751.3496 ],
        [750.93384],
        [747.7636 ],
        [744.0739 ],
        [747.34406],
        [748.9164 ],
        [747.83124],
        [750.3574 ],
        [751.9098 ],
        [752.8762 ],
        [754.5304 ],
        [755.16254],
        [755.15186],
        [755.6731 ],
        [753.83997],
        [754.97766],
        [754.79126],
        [754.1078 ],
        [753.77747],
        [753.6718 ],
        [754.1605 ],
        [752.1053 ],
        [751.88477],
        [750.98047]],

       [[611.7339 ],
        [693.8525 ],
        [716.9087 ],
        [729.5614 ],
        [739.79694],
        [744.3822 ],
        [746.6526 ],
        [748.75073],
        [748.46674],
        [745.72595],
        [751.99756],
        [754.3917 ],
        [754.08496],
        [756.4435 ],
        [749.24066],
        [748.91943],
        [746.57764],
        [748.52625],
        [751.2119 ],
        [752.1    ],
        [749.9865 ],
        [752.1324 ],
        [750.9765 ],
        [750.0293 ],
        [748.8616 ],
        [751.39307],
        [750.9811 ],
        [747.8153 ],
        [744.12885],
        [747.3982 ],
        [748.9717 ],
        [747.8893 ],
        [750.4157 ],
        [751.9693 ],
        [752.93713],
        [754.59186],
        [755.2253 ],
        [755.21594],
        [755.7379 ],
        [753.90704],
        [755.0443 ],
        [754.8587 ],
        [754.1763 ],
        [753.8465 ],
        [753.7413 ],
        [754.22974],
        [752.1764 ],
        [751.95624],
        [751.05273],
        [752.8589 ]],

       [[611.975  ],
        [693.09863],
        [716.2568 ],
        [730.537  ],
        [737.9367 ],
        [742.20624],
        [745.68823],
        [746.38293],
        [744.3202 ],
        [751.0078 ],
        [753.71387],
        [753.63074],
        [756.139  ],
        [749.04675],
        [748.79114],
        [746.494  ],
        [748.4724 ],
        [751.18176],
        [752.0897 ],
        [749.99164],
        [752.1478 ],
        [751.00146],
        [750.0614 ],
        [748.8991 ],
        [751.43384],
        [751.0265 ],
        [747.8656 ],
        [744.18256],
        [747.4514 ],
        [749.0264 ],
        [747.947  ],
        [750.4741 ],
        [752.02905],
        [752.9985 ],
        [754.6542 ],
        [755.2889 ],
        [755.2812 ],
        [755.80383],
        [753.97546],
        [755.1126 ],
        [754.92773],
        [754.2464 ],
        [753.91724],
        [753.8124 ],
        [754.30066],
        [752.2494 ],
        [752.0294 ],
        [751.12683],
        [752.9315 ],
        [752.4115 ]],

       [[611.7638 ],
        [692.5747 ],
        [717.10376],
        [728.74524],
        [735.8249 ],
        [741.26416],
        [743.3618 ],
        [742.28424],
        [749.57434],
        [752.73267],
        [752.9734 ],
        [755.69745],
        [748.7663 ],
        [748.6066 ],
        [746.37537],
        [748.397  ],
        [751.139  ],
        [752.0731 ],
        [749.99524],
        [752.1645 ],
        [751.03   ],
        [750.0986 ],
        [748.943  ],
        [751.4812 ],
        [751.0791 ],
        [747.9236 ],
        [744.2446 ],
        [747.513  ],
        [749.08936],
        [748.01324],
        [750.5408 ],
        [752.097  ],
        [753.06793],
        [754.72424],
        [755.3602 ],
        [755.354  ],
        [755.87744],
        [754.05164],
        [755.18823],
        [755.0042 ],
        [754.324  ],
        [753.99554],
        [753.89105],
        [754.37915],
        [752.3299 ],
        [752.11035],
        [751.2086 ],
        [753.01166],
        [752.4923 ],
        [754.11694]],

       [[611.6527 ],
        [693.1643 ],
        [715.4861 ],
        [726.7286 ],
        [734.9051 ],
        [738.9862 ],
        [739.32446],
        [747.4854 ],
        [751.29913],
        [752.01086],
        [755.0474 ],
        [748.35144],
        [748.33264],
        [746.1981 ],
        [748.2827 ],
        [751.07074],
        [752.0406 ],
        [749.98975],
        [752.1763 ],
        [751.05676],
        [750.1361 ],
        [748.9885 ],
        [751.5313 ],
        [751.135  ],
        [747.98566],
        [744.3113 ],
        [747.57904],
        [749.1569 ],
        [748.0842 ],
        [750.61194],
        [752.1694 ],
        [753.14185],
        [754.7986 ],
        [755.4358 ],
        [755.431  ],
        [755.955  ],
        [754.132  ],
        [755.26807],
        [755.0847 ],
        [754.40564],
        [754.0779 ],
        [753.97375],
        [754.4616 ],
        [752.4146 ],
        [752.1954 ],
        [751.29474],
        [753.09595],
        [752.5772 ],
        [754.20026],
        [756.0442 ]],

       [[611.8052 ],
        [692.09174],
        [713.68054],
        [725.8564 ],
        [732.7059 ],
        [735.04456],
        [744.44934],
        [749.20654],
        [750.59985],
        [754.08936],
        [747.736  ],
        [747.92334],
        [745.93066],
        [748.1072 ],
        [750.9613 ],
        [751.98083],
        [749.9672 ],
        [752.1776 ],
        [751.078  ],
        [750.1714 ],
        [749.0343 ],
        [751.58295],
        [751.19366],
        [748.0515 ],
        [744.38245],
        [747.64996],
        [749.22955],
        [748.1606 ],
        [750.68866],
        [752.2473 ],
        [753.2213 ],
        [754.8788 ],
        [755.5173 ],
        [755.5139 ],
        [756.0386 ],
        [754.2184 ],
        [755.354  ],
        [755.1714 ],
        [754.4935 ],
        [754.16644],
        [754.0627 ],
        [754.5503 ],
        [752.5057 ],
        [752.28674],
        [751.3871 ],
        [753.18646],
        [752.66846],
        [754.2898 ],
        [756.1318 ],
        [756.32275]],

       [[611.53613],
        [690.79047],
        [712.8663 ],
        [723.75696],
        [728.9059 ],
        [740.0726 ],
        [746.1775 ],
        [748.5539 ],
        [752.6975 ],
        [746.8446 ],
        [747.3337 ],
        [745.5489 ],
        [747.8589 ],
        [750.80664],
        [751.89575],
        [749.9336 ],
        [752.176  ],
        [751.1026 ],
        [750.2145 ],
        [749.0907 ],
        [751.64655],
        [751.2655 ],
        [748.1319 ],
        [744.4695 ],
        [747.7363 ],
        [749.3175 ],
        [748.2527 ],
        [750.78076],
        [752.3402 ],
        [753.31555],
        [754.973  ],
        [755.61255],
        [755.6107 ],
        [756.1358 ],
        [754.3186 ],
        [755.45337],
        [755.27155],
        [754.595  ],
        [754.26855],
        [754.16516],
        [754.65234],
        [752.6105 ],
        [752.3919 ],
        [751.49335],
        [753.2907 ],
        [752.7733 ],
        [754.39276],
        [756.2323 ],
        [756.4231 ],
        [755.91504]],

       [[611.26526],
        [690.2211 ],
        [710.9829 ],
        [720.1572 ],
        [733.78394],
        [741.79236],
        [745.5729 ],
        [750.6593 ],
        [745.5357 ],
        [746.4668 ],
        [744.98773],
        [747.49316],
        [750.5761 ],
        [751.7637 ],
        [749.87384],
        [752.1609 ],
        [751.1227 ],
        [750.25916],
        [749.1529 ],
        [751.718  ],
        [751.3469 ],
        [748.22363],
        [744.5691 ],
        [747.8356 ],
        [749.41833],
        [748.3578 ],
        [750.8854 ],
        [752.4454 ],
        [753.42175],
        [755.07904],
        [755.7192 ],
        [755.7186 ],
        [756.24396],
        [754.43   ],
        [755.5637 ],
        [755.38257],
        [754.7073 ],
        [754.38153],
        [754.2785 ],
        [754.76514],
        [752.7263 ],
        [752.50806],
        [751.6107 ],
        [753.4056 ],
        [752.88904],
        [754.5062 ],
        [756.34314],
        [756.53357],
        [756.0263 ],
        [756.3248 ]],

       [[611.1621 ],
        [688.96936],
        [707.7785 ],
        [724.8225 ],
        [735.4846 ],
        [741.24286],
        [747.674  ],
        [743.60364],
        [745.17944],
        [744.14856],
        [746.94055],
        [750.2205 ],
        [751.5502 ],
        [749.7637 ],
        [752.1145 ],
        [751.1255 ],
        [750.2959 ],
        [749.21344],
        [751.7915 ],
        [751.43317],
        [748.3224 ],
        [744.67773],
        [747.94403],
        [749.5288 ],
        [748.47314],
        [751.0001 ],
        [752.5606 ],
        [753.53796],
        [755.1947 ],
        [755.8355 ],
        [755.8362 ],
        [756.3616 ],
        [754.55115],
        [755.6836 ],
        [755.5032 ],
        [754.82916],
        [754.50415],
        [754.40137],
        [754.8874 ],
        [752.85175],
        [752.63385],
        [751.73785],
        [753.53015],
        [753.0143 ],
        [754.6291 ],
        [756.4631 ],
        [756.65326],
        [756.1467 ],
        [756.44476],
        [756.45593]],

       [[610.9165 ],
        [686.8102 ],
        [712.0086 ],
        [726.4757 ],
        [734.9979 ],
        [743.3251 ],
        [740.761  ],
        [743.27234],
        [742.89636],
        [746.1092 ],
        [749.6775 ],
        [751.21387],
        [749.5763 ],
        [752.01965],
        [751.10016],
        [750.3182 ],
        [749.269  ],
        [751.86536],
        [751.524  ],
        [748.4288 ],
        [744.7964 ],
        [748.0635 ],
        [749.65076],
        [748.60046],
        [751.12683],
        [752.68774],
        [753.6659 ],
        [755.3219 ],
        [755.96326],
        [755.965  ],
        [756.4906 ],
        [754.6836 ],
        [755.81464],
        [755.6349 ],
        [754.9623 ],
        [754.638  ],
        [754.5355 ],
        [755.0209 ],
        [752.98865],
        [752.7711 ],
        [751.8766 ],
        [753.6659 ],
        [753.151  ],
        [754.7631 ],
        [756.594  ],
        [756.7838 ],
        [756.278  ],
        [756.5753 ],
        [756.5864 ],
        [756.4728 ]],

       [[610.53125],
        [689.61584],
        [713.46375],
        [726.00256],
        [736.98553],
        [736.55286],
        [740.41516],
        [740.9968 ],
        [744.8302 ],
        [748.82495],
        [750.66614],
        [749.2471 ],
        [751.82666],
        [751.00793],
        [750.2943 ],
        [749.29224],
        [751.9159 ],
        [751.59766],
        [748.5226 ],
        [744.9051 ],
        [748.1748 ],
        [749.7659 ],
        [748.7218 ],
        [751.2482 ],
        [752.80994],
        [753.78906],
        [755.44464],
        [756.08655],
        [756.0896 ],
        [756.6151 ],
        [754.81177],
        [755.9414 ],
        [755.7622 ],
        [755.09106],
        [754.76733],
        [754.6652 ],
        [755.14984],
        [753.121  ],
        [752.9038 ],
        [752.0106 ],
        [753.7971 ],
        [753.2832 ],
        [754.8927 ],
        [756.7206 ],
        [756.91   ],
        [756.405  ],
        [756.7017 ],
        [756.71265],
        [756.599  ],
        [756.3434 ]],

       [[611.07996],
        [690.7081 ],
        [713.064  ],
        [727.8788 ],
        [730.3974 ],
        [736.16504],
        [738.11914],
        [742.85706],
        [747.47974],
        [749.7711 ],
        [748.6731 ],
        [751.45703],
        [750.7866 ],
        [750.1737 ],
        [749.24036],
        [751.907  ],
        [751.6225 ],
        [748.57404],
        [744.9754 ],
        [748.25183],
        [749.8498 ],
        [748.81366],
        [751.34247],
        [752.90674],
        [753.8885 ],
        [755.5449 ],
        [756.1885 ],
        [756.19336],
        [756.71967],
        [754.91974],
        [756.0487 ],
        [755.87036],
        [755.2006 ],
        [754.87775],
        [754.77606],
        [755.26025],
        [753.23425],
        [753.0175 ],
        [752.1257 ],
        [753.90985],
        [753.39667],
        [755.004  ],
        [756.8293 ],
        [757.0186 ],
        [756.5142 ],
        [756.81055],
        [756.8213 ],
        [756.70776],
        [756.4525 ],
        [756.28534]],

       [[611.27637],
        [690.4081 ],
        [714.73145],
        [721.5848 ],
        [730.0086 ],
        [733.9034 ],
        [739.93823],
        [745.4704 ],
        [748.41736],
        [747.78796],
        [750.8716 ],
        [750.4176 ],
        [749.95123],
        [749.1177 ],
        [751.8477 ],
        [751.6117 ],
        [748.59973],
        [745.0265 ],
        [748.3141 ],
        [749.92236],
        [748.8967 ],
        [751.4296 ],
        [752.99805],
        [753.9836 ],
        [755.6419 ],
        [756.28784],
        [756.29517],
        [756.82263],
        [755.0265 ],
        [756.1549 ],
        [755.9778 ],
        [755.3096 ],
        [754.98755],
        [754.8864 ],
        [755.3702 ],
        [753.3473 ],
        [753.1309 ],
        [752.24036],
        [754.02234],
        [753.5099 ],
        [755.11523],
        [756.9381 ],
        [757.1272 ],
        [756.62354],
        [756.9193 ],
        [756.9301 ],
        [756.81665],
        [756.56177],
        [756.39465],
        [756.62555]],

       [[611.2005 ],
        [691.50714],
        [709.0371 ],
        [721.212  ],
        [727.8158 ],
        [735.69055],
        [742.5256 ],
        [746.4198 ],
        [746.4712 ],
        [749.9914 ],
        [749.8523 ],
        [749.59875],
        [748.90955],
        [751.7315 ],
        [751.5641 ],
        [748.603  ],
        [745.0647 ],
        [748.36914],
        [749.99164],
        [748.9795 ],
        [751.5183 ],
        [753.0921 ],
        [754.08215],
        [755.7429 ],
        [756.3915 ],
        [756.4015 ],
        [756.9302 ],
        [755.1381 ],
        [756.266  ],
        [756.08997],
        [755.4234 ],
        [755.1024 ],
        [755.0018 ],
        [755.4852 ],
        [753.4655 ],
        [753.2495 ],
        [752.36035],
        [754.13983],
        [753.6283 ],
        [755.2314 ],
        [757.05164],
        [757.2406 ],
        [756.73773],
        [757.0331 ],
        [757.04376],
        [756.9304 ],
        [756.6759 ],
        [756.509  ],
        [756.7394 ],
        [756.7378 ]],

       [[611.44446],
        [687.7351 ],
        [708.7662 ],
        [719.156  ],
        [729.5904 ],
        [738.26086],
        [743.5036 ],
        [744.5341 ],
        [748.6861 ],
        [749.00354],
        [749.059  ],
        [748.5794 ],
        [751.5349 ],
        [751.4661 ],
        [748.5773 ],
        [745.0882 ],
        [748.4176 ],
        [750.0603 ],
        [749.06604],
        [751.6135 ],
        [753.1945 ],
        [754.1904 ],
        [755.8544 ],
        [756.5064 ],
        [756.5198 ],
        [757.05005],
        [755.2625 ],
        [756.39   ],
        [756.21533],
        [755.55066],
        [755.2307 ],
        [755.1306 ],
        [755.6138 ],
        [753.5975 ],
        [753.382  ],
        [752.49426],
        [754.2711 ],
        [753.7606 ],
        [755.36127],
        [757.1786 ],
        [757.36725],
        [756.8653 ],
        [757.1601 ],
        [757.1708 ],
        [757.05756],
        [756.8034 ],
        [756.63666],
        [756.8666 ],
        [756.86487],
        [759.02747]],

       [[610.6697 ],
        [687.39856],
        [706.8805 ],
        [720.8713 ],
        [732.1198 ],
        [739.27637],
        [741.713  ],
        [746.7791 ],
        [747.76025],
        [748.2661 ],
        [748.09155],
        [751.24005],
        [751.31256],
        [748.52637],
        [745.10767],
        [748.47253],
        [750.1426 ],
        [749.1717 ],
        [751.7298 ],
        [753.31915],
        [754.32153],
        [755.9884 ],
        [756.6437 ],
        [756.6601 ],
        [757.1917 ],
        [755.40906],
        [756.5355 ],
        [756.362  ],
        [755.6991 ],
        [755.38025],
        [755.2806 ],
        [755.7631 ],
        [753.7507 ],
        [753.5358 ],
        [752.64984],
        [754.42346],
        [753.91394],
        [755.5116 ],
        [757.32544],
        [757.5138 ],
        [757.0127 ],
        [757.30676],
        [757.3172 ],
        [757.2043 ],
        [756.9503 ],
        [756.78394],
        [757.01324],
        [757.0114 ],
        [759.1696 ],
        [760.10364]],

       [[610.6477 ],
        [686.23047],
        [708.5027 ],
        [723.3212 ],
        [733.13965],
        [737.55566],
        [743.9321 ],
        [745.87427],
        [747.03723],
        [747.31055],
        [750.74457],
        [751.0241 ],
        [748.3866 ],
        [745.069  ],
        [748.48816],
        [750.19855],
        [749.2603 ],
        [751.83484],
        [753.43665],
        [754.4481 ],
        [756.1199 ],
        [756.7795 ],
        [756.8    ],
        [757.3334 ],
        [755.5562 ],
        [756.6819 ],
        [756.50964],
        [755.8488 ],
        [755.53107],
        [755.43195],
        [755.9138 ],
        [753.90546],
        [753.6909 ],
        [752.80676],
        [754.5771 ],
        [754.0687 ],
        [755.66345],
        [757.47375],
        [757.6616 ],
        [757.1615 ],
        [757.45496],
        [757.4652 ],
        [757.35236],
        [757.09875],
        [756.93256],
        [757.16125],
        [757.15936],
        [759.3132 ],
        [760.24524],
        [761.2096 ]],

       [[610.44324],
        [687.2872 ],
        [710.68243],
        [724.2848 ],
        [731.46954],
        [739.7069 ],
        [743.0315 ],
        [745.15173],
        [746.08167],
        [749.939  ],
        [750.52423],
        [748.1044 ],
        [744.9337 ],
        [748.4356 ],
        [750.2064 ],
        [749.3147 ],
        [751.91516],
        [753.5357 ],
        [754.56104],
        [756.2406 ],
        [756.9069 ],
        [756.933  ],
        [757.46924],
        [755.6981 ],
        [756.82355],
        [756.653  ],
        [755.9945 ],
        [755.678  ],
        [755.57947],
        [756.0608 ],
        [754.05646],
        [753.8426 ],
        [752.95996],
        [754.7274 ],
        [754.2199 ],
        [755.81177],
        [757.6188 ],
        [757.8063 ],
        [757.3071 ],
        [757.59973],
        [757.6099 ],
        [757.4972 ],
        [757.244  ],
        [757.07794],
        [757.3063 ],
        [757.3042 ],
        [759.4536 ],
        [760.3838 ],
        [761.34607],

# What will be the Open Price on 1/3/2017

In [44]:
pred_data[0][49][0]

751.8084

751.8084 will be the predicted Open price on 1/3/2017